language: python
python:
  - "2.7"

sudo: required
services:
  - docker

cache:
  - pip

before_install:
  - docker-compose -f ./.travis-docker-compose.yml up -d

install:
  - docker exec -t notifier_testing bash -c 'pip install -r /edx/app/notifier/notifier/requirements.txt'
script:
  - docker exec -t notifier_testing bash -c 'cd /edx/app/notifier/notifier && coverage run /edx/app/notifier/notifier/manage.py test notifier'

after_success:
  - pip install -U codecov
  - docker exec notifier_testing /edx/app/notifier/notifier/run_coverage.sh
  - codecov
