language: python
matrix:
  allow_failures:
    - python: "3.6"
    - python: "3.7"
  include:
    - python: "2.7"
    - python: "3.6"
    - python: "3.7"
      dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - sudo rm -f /etc/boto.cfg && python manage.py test notifier
after_success:
  - coveralls
